//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public puesto()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int puesto_id { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string como_aplicar { get; set; }
        public string ubicacion { get; set; }
        public string compania { get; set; }
        public string logo { get; set; }
        public string Categoria { get; set; }
        public Nullable<double> Salario { get; set; }
        public Nullable<bool> estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
