//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol_operacion
    {
        public int id { get; set; }
        public int id_rol { get; set; }
        public int id_operacion { get; set; }
    
        public virtual operacione operacione { get; set; }
        public virtual rol rol { get; set; }
    }
}
