//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        public int id_solicitud { get; set; }
        public int solicitante { get; set; }
        public string nombre { get; set; }
        public string posicion { get; set; }
        public string empresa { get; set; }
        public Nullable<int> id_puesto { get; set; }
    
        public virtual puesto puesto { get; set; }
    }
}
